"""Initial

Revision ID: 649f665ee69f
Revises: 
Create Date: 2026-07-15 01:46:56.622434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '649f665ee69f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_destino', sa.String(length=255), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.Column('total_pessoas', sa.Integer(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trajetorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cargo_origem', sa.String(length=255), nullable=False),
    sa.Column('cargo_destino', sa.String(length=255), nullable=False),
    sa.Column('tempo_medio_meses', sa.Integer(), nullable=False),
    sa.Column('cursos_relacionados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faixa_investimento_medio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fonte_dado', postgresql.ENUM('real', 'sintetico', name='fonte_dado_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('disponibilidade_financeira_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('perfil_estruturado_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plano', postgresql.ENUM('free', 'premium', name='plano_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo_cargo', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('faixa_salarial_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('faixa_salarial_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requisitos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('url_original', sa.String(length=1000), nullable=False),
    sa.Column('hash_deduplicacao', sa.String(length=255), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('coletada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vagas_cidade_titulo_cargo', 'vagas', ['cidade', 'titulo_cargo'], unique=False)
    op.create_index(op.f('ix_vagas_hash_deduplicacao'), 'vagas', ['hash_deduplicacao'], unique=False)
    op.create_index(op.f('ix_vagas_url_original'), 'vagas', ['url_original'], unique=True)
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('plano', postgresql.ENUM('free', 'premium', name='plano_enum'), nullable=False),
    sa.Column('status_pagamento', postgresql.ENUM('ativo', 'pendente', 'cancelado', 'vencido', name='status_pagamento_enum'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_usuario_id'), 'assinaturas', ['usuario_id'], unique=False)
    op.create_table('curriculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('arquivo_url', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculos_usuario_id'), 'curriculos', ['usuario_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('proximo_cargo_sugerido', sa.String(length=255), nullable=False),
    sa.Column('tempo_estimado_meses', sa.Integer(), nullable=False),
    sa.Column('passos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('gerando', 'pronto', 'erro', name='status_roadmap_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_usuario_id'), 'roadmaps', ['usuario_id'], unique=False)
    op.create_table('roadmap_vagas',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roadmap_id', 'vaga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_vagas')
    op.drop_index(op.f('ix_roadmaps_usuario_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_curriculos_usuario_id'), table_name='curriculos')
    op.drop_table('curriculos')
    op.drop_index(op.f('ix_assinaturas_usuario_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_vagas_url_original'), table_name='vagas')
    op.drop_index(op.f('ix_vagas_hash_deduplicacao'), table_name='vagas')
    op.drop_index('ix_vagas_cidade_titulo_cargo', table_name='vagas')
    op.drop_table('vagas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('trajetorias')
    op.drop_table('clusters')
    # ### end Alembic commands ###
